import {db,runtime,getCatalog,owner,ApiError,digest} from './server';
import {pricingPolicy,printer} from './catalog';
import {calculateQuote,validateConfig,requireMaterialStock,InsufficientStockError,type Item,type Stats,type Quote} from './pricing';
export async function quoteItem(item:Item,fulfillment='pickup',withSlicer=false):Promise<Quote>{if(!!item.productId===!!item.uploadId)throw new ApiError('Choose a product or one uploaded model.');const {products,materials,profiles}=await getCatalog();const config=validateConfig(item.config);const material=materials.find(m=>m.id===config.material);if(!material)throw new ApiError('Choose an available material.');const product=item.productId?products.find(p=>p.id===item.productId&&p.available):undefined;if(item.productId&&!product)throw new ApiError('This object is not available.',404);let stats:Stats;let objectKey='';
 if(product){if(product.materialIds?.length&&!product.materialIds.includes(config.material))throw new ApiError('Choose one of this object’s available materials.');if(product.colorIds?.length&&!product.colorIds.includes(config.color))throw new ApiError('Choose one of this object’s available colors.');if(product.sizeOptions?.length&&!product.sizeOptions.includes(config.size))throw new ApiError('Choose an available size.');if(product.modelId){const stored=await db().prepare('SELECT stats FROM uploads WHERE id=?').bind(product.modelId).first<{stats:string}>();if(!stored)throw new ApiError('This object model is unavailable.',503);stats=JSON.parse(stored.stats);}else stats={dimensions:product.dimensions,volume:product.dimensions.reduce((a,b)=>a*b,1)*.19,triangles:0};}else{if(!item.uploadId)throw new ApiError('Choose a product or upload a model.');const upload=await db().prepare('SELECT stats,owner,object_key FROM uploads WHERE id=?').bind(item.uploadId).first<{stats:string;owner:string;object_key:string}>();if(!upload||upload.owner!==await owner(false))throw new ApiError('Upload this model again to continue.',404);stats=JSON.parse(upload.stats);objectKey=upload.object_key;}
 // Check configuration and bounds first, but let actual measurements precede estimated stock rejection.
 calculateQuote(config,material,stats,product,fulfillment,undefined,profiles,{checkStock:false});const snapshotId=digest(JSON.stringify({productId:item.productId,uploadId:item.uploadId,config,material,stats,fulfillment,profiles,pricingPolicy,printer,product,revision:runtime.SLICER_PROFILE_REVISION??'forma-profile-1'}));const cached=await db().prepare('SELECT data FROM quote_snapshots WHERE id=? AND created>?').bind(snapshotId,Date.now()-86400000).first<{data:string}>();if(cached){const result=JSON.parse(cached.data) as Quote;requireMaterialStock(material,result.grams);return result}if(!withSlicer||!objectKey)return calculateQuote(config,material,stats,product,fulfillment,undefined,profiles);if(!runtime.SLICER_URL)throw new ApiError('Automated print analysis is not connected yet. Your price is an estimate; the studio will review it before production.',503);
  try{const file=await runtime.BUCKET.get(objectKey);if(!file)throw new Error('Missing model');const form=new FormData();form.set('file',new Blob([await file.arrayBuffer()]),objectKey.endsWith('.3mf')?'model.3mf':'model.stl');form.set('config',JSON.stringify({...config,layerHeight:profiles.find((p:{id:string;layer:number})=>p.id===config.quality)?.layer,density:material.density}));const slicerEndpoint=runtime.SLICER_URL.endsWith('/slice')?runtime.SLICER_URL:new URL('/slice',runtime.SLICER_URL).toString();const res=await fetch(slicerEndpoint,{method:'POST',headers:runtime.SLICER_TOKEN?{Authorization:'Bearer '+runtime.SLICER_TOKEN}:{},body:form,signal:AbortSignal.timeout(25000)});if(!res.ok)throw new Error('Slicer unavailable');const data=await res.json() as {grams:number;minutes:number};const result=calculateQuote(config,material,stats,undefined,fulfillment,data,profiles);await db().prepare('INSERT INTO quote_snapshots(id,data,created) VALUES (?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,created=excluded.created').bind(snapshotId,JSON.stringify(result),Date.now()).run();return result}catch(error){if(error instanceof InsufficientStockError)throw error;throw new ApiError('Print analysis is unavailable. Your estimate is saved; the studio can review it manually.',503)}
}
