export interface FallbackReply { text: string; suggestions: string[] }

export function getFallbackSupportReply(userQuery: string, requestedLang?: 'en' | 'ar'): FallbackReply {
  const query = userQuery.trim().toLowerCase();
  const ar = requestedLang === 'ar' || (requestedLang !== 'en' && /[\u0600-\u06FF]/.test(query));
  const has = (words: string[]) => words.some(word => query.includes(word));
  const reply = (en: string, arabic: string, enSuggestions: string[], arSuggestions: string[]): FallbackReply => ({ text: ar ? arabic : en, suggestions: ar ? arSuggestions : enSuggestions });
  const paymentEn = 'Reserve your order, then contact studio support with your order number to arrange an in-person meeting at Alhussan International School or Al Huwaylat in Jubail. Staff confirms the exact time, meeting point and final quote before you visit or pay. Pay the full confirmed amount and ask for a receipt. Printing starts only after staff verifies full payment. Finished objects are collected locally for free; delivery is not available.';
  const paymentAr = 'احجز طلبك ثم تواصل مع دعم الاستوديو برقم الطلب لترتيب لقاء شخصي في مدرسة الحصان العالمية أو الحويلات في الجبيل. يؤكد الفريق الوقت ونقطة اللقاء والسعر النهائي قبل الزيارة أو الدفع. ادفع المبلغ كاملًا واطلب إيصالًا. تبدأ الطباعة بعد تأكيد الفريق للدفع كاملًا. الاستلام المحلي مجاني ولا تتوفر خدمة توصيل.';
  const paymentSuggestionsEn = ['Arrange payment with staff', 'Track my reservation', 'How is price calculated?'];
  const paymentSuggestionsAr = ['رتب الدفع مع الفريق', 'تتبع حجزي', 'كيف يتم حساب السعر؟'];
  const code = userQuery.toUpperCase().match(/JBL-[A-Z0-9]{6,12}/)?.[0];
  if (code || has(['track', 'status', 'where is my order', 'order number', 'تتبع', 'حالة الطلب', 'وين طلبي', 'رقم الطلب'])) {
    return reply(`${code ? 'Order reference: ' + code + '. ' : ''}Open /track and enter your order number and Saudi mobile number. Your reservation begins as awaiting payment. After staff confirms full payment, you can follow review, printing, finishing and ready-for-pickup updates. Sign in to view orders placed with your account, or submit a support ticket if you need help.`, `${code ? 'رقم الطلب: ' + code + '. ' : ''}افتح /track وأدخل رقم الطلب ورقم الجوال السعودي. يبدأ الحجز بانتظار الدفع. بعد تأكيد الفريق للدفع كاملًا يمكنك متابعة المراجعة والطباعة والتشطيب والجاهزية للاستلام. سجل الدخول لعرض طلبات حسابك أو أرسل تذكرة دعم للمساعدة.`, ['Track an order', 'Payment and pickup steps', 'Speak to the studio'], ['تتبع طلب', 'خطوات الدفع والاستلام', 'تواصل مع الاستوديو']);
  }
  if (has(['price', 'cost', 'quote', 'how much', 'sar', 'riyal', 'سعر', 'تكلفة', 'اسعار', 'أسعار', 'بكم', 'ريال'])) {
    return reply('Prints start at SAR 39. Custom quotes use PLA weight at SAR 0.55 per gram and machine time at SAR 3.50 per hour, with your quantity, quality and finish included. Volume savings: 2+ prints save 5%, 5+ save 10% and 10+ save 15%. Optional sanding is SAR 20 per print. Local pickup is free. Upload STL or 3MF in /lab for an estimate; staff confirms the final quote before you pay. Full payment must be verified before printing.', 'تبدأ الطباعة من 39 ريال. تُحسب الأسعار بحسب وزن PLA بسعر 0.55 ريال للجرام ووقت الطابعة بسعر 3.50 ريال للساعة، مع الكمية والجودة والتشطيب. وفّر مع الكمية: قطعتان أو أكثر 5%، و5 قطع أو أكثر 10%، و10 قطع أو أكثر 15%. الصنفرة اختيارية بسعر 20 ريال للقطعة. الاستلام المحلي مجاني. ارفع STL أو 3MF في /lab للحصول على تقدير؛ يؤكد الفريق السعر النهائي قبل الدفع. يجب تأكيد الدفع كاملًا قبل الطباعة.', ['Get a model quote', 'Payment and pickup steps', 'Available PLA colours'], ['احسب سعر نموذجي', 'خطوات الدفع والاستلام', 'ألوان PLA المتوفرة']);
  }
  if (has(['pay', 'cash', 'pickup', 'delivery', 'shipping', 'location', 'where', 'jubail', 'alhussan', 'huwaylat', 'دفع', 'نقد', 'استلام', 'توصيل', 'شحن', 'موقع', 'وين', 'الجبيل', 'الحصان', 'الحويلات'])) return reply(paymentEn, paymentAr, paymentSuggestionsEn, paymentSuggestionsAr);
  if (has(['printer', 'creality', 'ender', 'size', 'dimension', 'max', 'volume', 'height', 'طابعة', 'اندر', 'حجم', 'أبعاد', 'ابعاد', 'مساحة'])) {
    return reply('We print on a Creality Ender-3 V3 SE with a 220 × 220 × 250 mm build volume (Z is height) and a 0.4 mm nozzle. The Lab checks whether your model fits. Choose Draft (0.28 mm), Standard (0.20 mm), Smooth (0.16 mm) or Detail (0.12 mm). Upload STL or 3MF files up to 15 MB.', 'نطبع باستخدام Creality Ender-3 V3 SE بمساحة 220 × 220 × 250 مم (Z هو الارتفاع) وفوهة 0.4 مم. يتحقق المختبر من ملاءمة النموذج. اختر سريع (0.28 مم) أو قياسي (0.20 مم) أو ناعم (0.16 مم) أو دقيق (0.12 مم). نقبل STL و3MF حتى 15 MB.', ['Check my model in the Lab', 'Available PLA colours', 'Print pricing'], ['افحص نموذجي في المختبر', 'ألوان PLA المتاحة', 'أسعار الطباعة']);
  }
  if (has(['colour', 'color', 'pla', 'filament', 'material', 'ألوان', 'الوان', 'لون', 'خامة', 'خامات', 'فيلامينت', 'مواد'])) {
    return reply('We stock PLA in eight colours: Cloud White, Charcoal Black, Sage Grey, Sea Blue, Coral Red, Clear Transparent, Sunshine Yellow and Leaf Green. PLA works well for indoor desk accessories, organisers and display objects. Keep it away from high heat. Pick a colour and see it on your 3D object before ordering.', 'تتوفر خامة PLA بثمانية ألوان: الأبيض السحابي، الأسود الفحمي، الرمادي، الأزرق البحري، الأحمر المرجاني، الشفاف، الأصفر والأخضر. تناسب القطع المكتبية والمنظمات وقطع العرض الداخلية. أبعدها عن الحرارة العالية. اختر لونًا وشاهده على القطعة ثلاثية الأبعاد قبل الطلب.', ['Browse objects', 'Get a model quote', 'Payment and pickup steps'], ['تصفح القطع', 'احسب سعر نموذجي', 'خطوات الدفع والاستلام']);
  }
  if (has(['upload', 'stl', '3mf', 'obj', 'file', 'رفع', 'ملف', 'صيغة'])) return reply('Upload STL or 3MF files up to 15 MB in /lab. The Lab checks geometry, dimensions and printer fit, then estimates grams, time and price. OBJ is not supported. Your private upload is used for your order and is not automatically published in the catalogue.', 'ارفع STL أو 3MF حتى 15 MB في /lab. يفحص المختبر الشكل والأبعاد وملاءمة الطابعة ثم يقدر الوزن والوقت والسعر. صيغة OBJ غير مدعومة. يبقى ملفك خاصًا بطلبك ولا يُنشر تلقائيًا في المجموعة.', ['Open the Lab', 'Maximum print size', 'Print pricing'], ['افتح المختبر', 'أقصى حجم للطباعة', 'أسعار الطباعة']);
  if (has(['human', 'ticket', 'support', 'problem', 'staff', 'contact', 'إنسان', 'فريق', 'دعم', 'تذكرة', 'مشكلة', 'تواصل'])) return reply('Open the Support ticket tab and send your name, email, order number (if you have one) and message. Studio staff can help arrange your payment meeting, review a model, or resolve an order issue. Keep your ticket reference for follow-up.', 'افتح تبويب تذكرة الدعم وأرسل الاسم والبريد ورقم الطلب إن وجد ورسالتك. يساعدك فريق الاستوديو في ترتيب لقاء الدفع ومراجعة النموذج وحل مشاكل الطلب. احتفظ برقم التذكرة للمتابعة.', ['Payment and pickup steps', 'Track an order', 'Model requirements'], ['خطوات الدفع والاستلام', 'تتبع طلب', 'متطلبات النموذج']);
  return reply('Welcome to Forma3D, a 3D printing studio in Jubail using the Creality Ender-3 V3 SE and eight PLA colours. Ask about print pricing, model sizes, STL/3MF uploads, payment and local pickup, or tracking a reservation.', 'مرحبًا بك في فورما3D، استوديو الطباعة ثلاثية الأبعاد في الجبيل باستخدام Creality Ender-3 V3 SE وثمانية ألوان PLA. اسأل عن الأسعار وأحجام النماذج ورفع STL/3MF والدفع والاستلام المحلي وتتبع الحجز.', ['How is price calculated?', 'Available PLA colours', 'Payment and pickup steps', 'Track an order'], ['كيف يُحسب السعر؟', 'ألوان PLA المتاحة', 'خطوات الدفع والاستلام', 'تتبع طلب']);
}
