'use client';
import { useCallback, useEffect, useState } from 'react';
import { Loader2, Mail, MessageCircle, RefreshCw } from 'lucide-react';

type Ticket = { id: string; name: string; email: string; phone: string; order_id?: string; subject: string; message: string; status: string; response?: string; created: number };
export default function SupportInbox({ ar }: { ar: boolean }) {
  const t = (en: string, arabic: string) => ar ? arabic : en;
  const [tickets, setTickets] = useState<Ticket[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const refresh = useCallback(async () => {
    setBusy(true); setError('');
    try { const response = await fetch('/api/support/tickets'); const data = await response.json() as { tickets: Ticket[]; error?: string }; if (!response.ok) throw new Error(data.error ?? 'Could not load tickets.'); setTickets(data.tickets); } catch (err) { setError(err instanceof Error ? err.message : 'Try again.'); } finally { setBusy(false); }
  }, []);
  useEffect(() => { queueMicrotask(() => void refresh()); }, [refresh]);
  return <div className="support-inbox"><div className="support-inbox-heading"><p>{t('Arrange payment meetings and respond to customer requests. Use the supplied contact details to agree the time and place.', 'رتب لقاءات الدفع ورد على طلبات العملاء. استخدم بيانات التواصل للاتفاق على الوقت والمكان.')}</p><button type="button" className="secondary-button" disabled={busy} onClick={() => void refresh()}><RefreshCw size={15} />{t('Refresh', 'تحديث')}</button></div>{error && <p className="journey-error" role="alert">{error}</p>}{busy && !tickets.length && <p><Loader2 className="spin" size={18} />{t('Loading requests…', 'نحمّل الطلبات…')}</p>}{!busy && !tickets.length && <div className="empty-state"><MessageCircle size={28} /><h2>{t('All caught up.', 'كل شيء محدث.')}</h2><p>{t('New customer requests will appear here.', 'تظهر طلبات العملاء الجديدة هنا.')}</p></div>}{tickets.map(ticket => <details key={ticket.id} className="support-inbox-ticket"><summary><div><strong>{ticket.subject}</strong><span>{ticket.name} / {ticket.id}{ticket.order_id && ' / ' + ticket.order_id}</span></div><span>{t(({ open: 'Open', in_progress: 'In progress', resolved: 'Resolved', closed: 'Closed' } as Record<string, string>)[ticket.status] ?? ticket.status, ({ open: 'مفتوحة', in_progress: 'قيد العمل', resolved: 'تم الحل', closed: 'مغلقة' } as Record<string, string>)[ticket.status] ?? ticket.status)}</span></summary><div className="support-inbox-content"><p>{ticket.message}</p><a className="journey-text-button" href={`mailto:${ticket.email}?subject=${encodeURIComponent('Forma3D / ' + ticket.id)}`}><Mail size={16} />{ticket.email}</a>{ticket.phone && <a className="journey-text-button" href={'tel:' + ticket.phone.replace(/[^+0-9]/g, '')} dir="ltr">{ticket.phone}</a>}<form onSubmit={async event => {
      event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); setError('');
      try { const response = await fetch('/api/support/tickets', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id: ticket.id, status: form.get('status'), response: form.get('response') }) }); const data = await response.json() as { error?: string }; if (!response.ok) throw new Error(data.error ?? 'Could not save response.'); await refresh(); } catch (err) { setError(err instanceof Error ? err.message : 'Try again.'); } finally { setBusy(false); }
    }}><label>{t('Request status', 'حالة الطلب')}<select name="status" defaultValue={ticket.status}>{[['open', 'Open', 'مفتوحة'], ['in_progress', 'In progress', 'قيد العمل'], ['resolved', 'Resolved', 'تم الحل'], ['closed', 'Closed', 'مغلقة']].map(([value, en, arabic]) => <option key={value} value={value}>{t(en, arabic)}</option>)}</select></label><label>{t('Saved response / studio notes', 'الرد المحفوظ / ملاحظات الاستوديو')}<textarea name="response" defaultValue={ticket.response ?? ''} maxLength={2000} rows={3} /></label><small>{t('This saves the response. Contact the customer to send meeting details.', 'هذا يحفظ الرد. تواصل مع العميل لإرسال تفاصيل اللقاء.')}</small><button className="primary-button" disabled={busy}>{t('Save request update', 'حفظ تحديث الطلب')}</button></form></div></details>)}</div>;
}
